# Data Layout for the improted text files from NC State Board of Elections
abs_dtypes = {
    'county_desc': 'str',
    'voter_reg_num': 'int64',
    'ncid': 'str',
    'voter_last_name': 'str',
    'voter_first_name': 'str',
    'voter_middle_name': 'str',
    'race': 'str',
    'ethnicity': 'str',
    'gender': 'str',
    'age': 'uint8',
    'voter_street_address': 'str',
    'voter_city': 'str',
    'voter_state': 'str',
    'voter_zip': 'str',
    'ballot_mail_street_address': 'str',
    'ballot_mail_city': 'str',
    'ballot_mail_state': 'str',
    'ballot_mail_zip': 'str',
    'other_mail_addr1': 'str',
    'other_mail_addr2': 'str',
    'other_city_state_zip': 'str',
    'relative_request_name': 'str',
    'relative_request_address': 'str',
    'relative_request_city': 'str',
    'relative_request_state': 'str',
    'relative_request_zip': 'str',
    'election_dt': 'object',
    'voter_party_code': 'str',
    'precinct_desc': 'str',
    'cong_dist_desc': 'str',
    'nc_house_desc': 'str',
    'nc_senate_desc': 'str',
    'ballot_req_delivery_type': 'str',
    'ballot_req_type': 'str',
    'ballot_request_party': 'str',
    'ballot_req_dt': 'object',
    'ballot_send_dt': 'object',
    'ballot_rtn_dt': 'object',
    'ballot_rtn_status': 'str',
    'site_name': 'str',
    'sdr': 'str',
    'mail_veri_status': 'str'
}
abs_dates = ['election_dt', 'ballot_req_dt', 'ballot_send_dt', 'ballot_rtn_dt']
abs_dateformat = "%m/%d/%Y"

voter_dtypes = {
    'county_id': 'int64',
    'county_desc': 'str',
    'voter_reg_num': 'int64',
    'ncid': 'str',
    'last_name': 'str',
    'first_name': 'str',
    'middle_name': 'str',
    'name_suffix_lbl': 'str',
    'status_cd': 'str',
    'voter_status_desc': 'str',
    'reason_cd': 'str',
    'voter_status_reason_desc': 'str',
    'res_street_address': 'str',
    'res_city_desc': 'str',
    'state_cd': 'str',
    'zip_code': 'str',
    'mail_addr1': 'str',
    'mail_addr2': 'str',
    'mail_addr3': 'str',
    'mail_addr4': 'str',
    'mail_city': 'str',
    'mail_state': 'str',
    'mail_zipcode': 'str',
    'full_phone_number': 'str',
    'confidential_ind': 'str',
    'registr_dt': 'object',
    'race_code': 'str',
    'ethnic_code': 'str',
    'party_cd': 'str',
    'gender_code': 'str',
    'birth_year': 'uint32',
    'age_at_year_end': 'uint32',
    'birth_state': 'str',
    'drivers_lic': 'str',
    'precinct_abbrv': 'str',
    'precinct_desc': 'str',
    'municipality_abbrv': 'str',
    'municipality_desc': 'str',
    'ward_abbrv': 'str',
    'ward_desc': 'str',
    'cong_dist_abbrv': 'str',
    'super_court_abbrv': 'str',
    'judic_dist_abbrv': 'str',
    'nc_senate_abbrv': 'str',
    'nc_house_abbrv': 'str',
    'county_commiss_abbrv': 'str',
    'county_commiss_desc': 'str',
    'township_abbrv': 'str',
    'township_desc': 'str',
    'school_dist_abbrv': 'str',
    'school_dist_desc': 'str',
    'fire_dist_abbrv': 'str',
    'fire_dist_desc': 'str',
    'water_dist_abbrv': 'str',
    'water_dist_desc': 'str',
    'sewer_dist_abbrv': 'str',
    'sewer_dist_desc': 'str',
    'sanit_dist_abbrv': 'str',
    'sanit_dist_desc': 'str',
    'rescue_dist_abbrv': 'str',
    'rescue_dist_desc': 'str',
    'munic_dist_abbrv': 'str',
    'munic_dist_desc': 'str',
    'dist_1_abbrv': 'str',
    'dist_1_desc': 'str',
    'vtd_abbrv': 'str',
    'vtd_desc': 'str'
}
voter_dates = ['registr_dt']
voter_dateformat = "%m/%d/%Y"

voterhist_dtypes = {
    'county_id': 'int64',
    'county_desc': 'str',
    'voter_reg_num': 'int64',
    'election_lbl': 'str',
    'election_desc': 'str',
    'voting_method': 'str',
    'voted_party_cd': 'str',
    'voted_party_desc': 'str',
    'pct_label': 'str',
    'pct_description': 'str',
    'ncid': 'str',
    'voted_county_id': 'int64',
    'voted_county_desc': 'str',
    'vtd_label': 'str',
    'vtd_description': 'str'
}
voterhist_dates = []
voterhist_dateformat = "%m/%d/%Y"
